name: 'starminga'
keywords: 'health, wellbeing, well-being, lifestyle, life-style, fashion, models'
description: 'because june only has 30 days'
subdescription: "and we're tired of wearing pyjamas"

url: https://starmin.ga
baseurl: ''
port: 8456
permalink: /:title/

encoding: utf-8

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "list"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, .sass-cache, README.md]
include: [_pages]
